#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Build Docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    if [ -z "$RASTER_VISION_REPO" ]
    then
        BASE_IMAGE="quay.io/azavea/raster-vision:cpu-latest"
    else
        BASE_IMAGE="raster-vision-cpu"
    fi

    docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -t raster-vision-fastai -f Dockerfile .
fi
